edition = "2023";

import "google/protobuf/timestamp.proto";

option go_package = "github.com/joshstrohminger/TorrentProcessor/internal/api";

service ControlService {
  rpc Refresh(RefreshRequest) returns (Empty);
}

message Empty {}

message RefreshRequest {
  Reason reason = 1;
  google.protobuf.Timestamp when = 2;
  string hash = 3; // Optional hash of the torrent this is relevant to.
  string name = 4; // Optional name of the torrent this is relevant to.

  enum Reason {
    Added = 0;
    Processing = 1;
    Processed = 2;
    Error = 3;
    Warning = 4;
  }
}
